Additional settings to control the WebAPI-Calls after an callback from the bridge occurred
iobroker-community-adapters/ioBroker.nuki-extended pull request #102
Opened 2020-10-31 08:00 UTC by Matze2010

2021-07-20 09:19 UTC, Apollon77 commented
@Matze2010 SOrry for the late check, could you please rebase your PR and also add the timeout to io-package native with the ddefault value? Thank you

2022-06-03 18:19 UTC, theimo1221 requested changes

2022-06-03 18:19 UTC, theimo1221 commented on nuki-extended.js
> +							setTimeout(getWebApi, adapter.config.additionalWebApiTimeout*1000);
To resolve Mergeconflict, this would need to be:
`setTimeout(() => {nukiWebApi.getWebApi()}, adapter.config.additionalWebApiTimeout * 1000);`

2022-06-03 19:38 UTC, Apollon77 commented
I incorporated manually

2022-06-03 19:38 UTC, closed without merging